name: tflint

on:
  push:
    branches:
      - main
    paths:
      - example/infra/**
      - .github/workflows/tflint.yml
  pull_request:
    paths:
      - example/infra/**
      - .github/workflows/tflint.yml

jobs:
  lints:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.tflint.d/plugins
          key: tflint-v2-${{ hashFiles('.tflint.hcl') }}
          restore-keys: |
            tflint-v2-

      - uses: terraform-linters/setup-tflint@4cb9feea73331a35b422df102992a03a44a3bb33 # v6.2.1

      - run: tflint --init
        working-directory: example/infra

      - run: tflint -f compact
        working-directory: example/infra
